### ISSUE TITLE
PGS scoring files column names: undocumented column in the schema: 'OR'

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#147]
Some PGS scoring files include an undocumented column in the schema: 'OR'.

Is it a mistake in these files or is it a missing schema documentation entry in here? In any case, it is not consistent across PGS scoring files. Here I provide two inconsistent examples, but this issue seems to happen throughout many of the PGS scoring files provided in the ftp server.

## Example: PGS000001.txt.gz contains the "OR" column

```bash
curl -s 'http://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/PGS000001/ScoringFiles/PGS000001.txt.gz' | gunzip -c | grep -P '\bOR\b'
```

```bash
rsID	chr_name	effect_allele	reference_allele	effect_weight	locus_name	OR
```

## Example: PGS000004.txt.gz does not contain the "OR" column

```bash
curl -s 'http://ftp.ebi.ac.uk/pub/databases/spot/pgs/scores/PGS000004/ScoringFiles/PGS000004.txt.gz' | gunzip -c | grep -P '\bchr_name\b'
```

```
chr_name	chr_position	effect_allele	reference_allele	effect_weight	allelefrequency_effect
```

**Comment by smlmbrt** [comment]
It's not a mistake, but it is an omission from the documentation. Sometimes the authors only give an Odds Ratio (OR) or Hazard Ratio (HR) as a weight for the PGS. In these cases we need to turn the OR/HR into an effect_weight and we do this by taking the log, as is customary when deriving PGS. We leave the OR/HR column in the scoring file to reflect how the score was originally provided by the authors.

**Comment by ens-lgil** [comment]
The documentation on the [Download](https://www.pgscatalog.org/downloads/#dl_ftp_scoring) page has been updated.
