### ISSUE TITLE
Is the `reference_allele` field in scoring files mandatory or optional?

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#148]
In your [medRxiv preprint](https://www.medrxiv.org/content/10.1101/2020.05.20.20108217v1.full.pdf), page 14, Supplemental Note 1, it reads **Suggested**.

Does that mean optional?

**Comment by smlmbrt** [comment]
Yes, it's _optional_. Ideally everyone would provide it as it makes the variant identification less ambiguous, but a high proportion of scores only contain the effect_allele. Thanks for pointing this out, 
we'll update the documentation to reflect this.

**Comment by ramiromagno** [comment]
Thank you for the clarification.
