### ISSUE TITLE
Recode 'NR' as null in JSON responses

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#149]
Oftentimes that are missing values which come coded as `"NR"` (for "Not Reported", I believe).

For the REST API user it would best if these came as `null` in the JSON responses. I already have to re-code `null` values to `NA` (Not Available) anyway. I don't know I easy it would be for you to do this, but if you could do this re-coding server-side it would simplify and improve efficiency of parsing on the client side.

Some examples of object keys whose values I found to be `"NR"`:

```
"ancestry_free": "NR"
"ancestry_country": "Australia, U.K., NR, U.S."
"variants_genomebuild": "NR"
"ancestry_free": "NR"
"ancestry_broad": "NR"
"ancestry_country": "NR"
"method_params": "NR"
"ancestry_country": "U.S., Australia, Canada, NR"
```

Not sure about those cases where the value is not a single `"NR"`, e.g., `"Australia, U.K., NR, U.S."` or `"U.S., Australia, Canada, NR"`. It is probably best to leave these cases as it is.

**Comment by ens-lgil** [comment]
Dear @ramiromagno,

Sorry for the late reply.
This ancestry data comes from the NHGRI-EBI GWAS Catalog. 
As we collaborate closely with them, we want to match the data and information they provide. That is why we keep the "NR", whenever they are used in the GWAS Catalog, to avoid discrepancies between the 2 Catalogs.

Best regards,
Laurent
