### ISSUE TITLE
REST API: values that are "UNKNOWN" should (probably) be replaced with null

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#153]
I am guessing this is something that needs to be corrected at the database level, and not at the REST API server level.

Example:

```bash
curl -X GET "https://www.pgscatalog.org/rest/performance/search?pgs_id=PGS000004&offset=0&limit=20&format=json" -H  "accept: application/json" | jq '.' | grep -in "unknown"
```

```
56:                "name_full": "UNKNOWN"
76:                "name_full": "UNKNOWN"
676:                "name_full": "UNKNOWN"
```

**Comment by ens-lgil** [comment]
Dear @ramiromagno,

Good point!
We replaced these *UNKNOWN* by the value of the corresponding `name_short`, to be consistent with other similar entries in the database.
It will be visible in the next data release.

Best regards,
Laurent
