### ISSUE TITLE
REST API: documentation for the Cohort_extended schema resulting from /rest/cohort/{cohort_symbol} different from actual response

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#156]
The schema for the response from `/rest/cohort/{cohort_symbol}` is a `Cohort_extended` object.

According to the documentation, the object `associated_pgs_ids` should be an array. Both the schema description and the cached response example given agree with this. However, an actual response returns `associated_pgs_ids` as an object of two elements: `development` and `evaluation`. I believe the documentation needs an update.

## Documentation of Cohort_extended schema

![cohort_extended](https://user-images.githubusercontent.com/19862384/105653263-4255ac80-5eb3-11eb-9ba5-6512ef5693bb.png)

## Example value

![cohort_extended2](https://user-images.githubusercontent.com/19862384/105653274-47b2f700-5eb3-11eb-8697-b893c40da20d.png)

## Actual response from /rest/cohort/ABCFS

![cohort_extended3](https://user-images.githubusercontent.com/19862384/105653342-7df07680-5eb3-11eb-9dc5-6c3ecce6ab75.png)

**Comment by ens-lgil** [comment]
Dear @ramiromagno,

Yes, you are right. I am going to update the schema documentation.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
This is now fixed
