### ISSUE TITLE
BUG: REST API: https://www.pgscatalog.org/rest/cohort/CARE_b?format=json is empty

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#162]
The endpoint `/rest/cohort/` for cohort CARE_b returns 200 but is empty. However, this cohort exists, e.g., it is associated with [PGS000010](https://www.pgscatalog.org/score/PGS000010/), PPM000015 and PSS000009.

**Comment by ramiromagno** [comment]
Also, all these cohorts can't be queried with `/rest/cohort`:

AtheroRemo
CADomics
MIGen
Angio-Lueb
FamHS
GMetS
GoKinD
DaHS
Immunochip
iPSYCH
DiscovEHR
AFGen
23andMe
CARDIoGRAMplusC4D
GenomEUtwin
CoLaus
InCHIANTI
IPO-Porto
Poland
ProMPT
ProtecT
Pegasus
CaP Genes
Ghana
ProHealth
deCODE CAD
AtheroRemo 1
AtheroRemo 2
Migen
BioVU
Munich MI
TwinsUK
Marshfield
Iowa
NordicDB
Seattle
HeOCS
Sisters
CopBCS
Georgetown
G-FaST
eMERGE
iCOGS
PEGASUS_PCa
PANDoRA
Toronto
Yale
Iowa-Mayo
LifeLines
MyCode
Vanderbilt
Airwave
Cilento
Czech post-MONICA
Generation R
INGI-Carlantino
INGI-Val Borbera
LIFE-Adult
LIFE-Child
Living-Biobank
DNA_Lacunar
Glasgow
Finland
Aarhus
CeRePP
Gene-PARE
Hawaiian colo2&3
cgr
ColoCare
Spain
Tromso
Harvard
CanSS
Resolucent
BioVu
Umea
Karolinska
conFIRM
Leeds
Moscow
SpBCS
FrBCS
BBCS_b
NeuBCS
Hawaiian Colo2&3
EpiHealth
GenomeAsia100K
FinnGen

**Comment by ens-lgil** [comment]
Dear @ramiromagno,

Thank you for reporting this issue.
This was a tiny bug in the REST API and it is now fixed.

Best regards,
Laurent
