### ISSUE TITLE
Consider making the "stage" annotation a data value of json elements

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#167]
In the PGS Catalog objects returned by REST API endpoints we see that the "stage" annotation of `pgs_ids` and samples are always done implicitly, i.e., in the name of keys of parent JSON elements, e.g.:

- objects returned by `/rest/score` includes objects `samples_variants` and `samples_training`, that then include the actual samples whose stage annotation has to be read from the parent elements, i.e, `samples_variants` corresponds to samples annotated with stage being "gwas", or "gwas variants", or perhaps "discovery", and `samples_training` ought to be annotated with "training". It would be better if these data were actually values, and not keys of parent elements, as it is now.
- the same happens, e.g., with `associated_pgs_ids`, which is split into `development` and `evaluation`, again two stage annotations of `pgs_ids` that would be best moved out of the parent elements' names by creating a new key:value pair ("stage": "development" or "stage": "evaluation").

Would it not be better to settle down on a new categorical variable, named "stage", whose possible levels would be:

- "discovery" (or other term you might prefer)
- "training"
- "development" (catch-all term for either "discovery" or "training")
- "evaluation"

and then annotate PGSes and samples with "stage": <stage level>.

This will decrease the current nesting level where this info is needed and make the parsing more straightforward on the user end. Here's a scribble indicating where I think changes would be required: [out.pdf](https://github.com/PGScatalog/PGS_Catalog/files/5932406/out.pdf).

**Comment by smlmbrt** [comment]
I think at the moment we will stick with the labels in the current catalog and paper. We plan to do some user outreach this year, and will poll them for any confusing re labelling of the different stages of PGS studies captured in the Catalog.
