### ISSUE TITLE
EFO trait "Orphanet_130" (Brugada syndrome) is not found

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#178]
Hi PGS Catalog team,

On the website, searching for the trait "Orphanet_130" shows two results:

![snap](https://user-images.githubusercontent.com/19862384/116800320-f3459600-aaf7-11eb-80d2-b7f2a65c3068.png)

but clicking on the Brugada syndrome trait gives an error 404.

On the REST API the response to `https://www.pgscatalog.org/rest/trait/Orphanet_130?include_children=0&format=json` is 200 but empty.

**Comment by ens-lgil** [comment]
Dear @ramiromagno,

Thank you for spotting this issue!
This is a redirection problem for both the website and the REST API. I am working on it and will let you know when this is fixed.

Best regards,
Laurent

**Comment by ens-lgil** [comment]
This is fixed now.
Thanks again for the report!

Best regards,
Laurent
