### ISSUE TITLE
sample size for PGS000737 does not match source publication's values

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#179]
The score https://www.pgscatalog.org/score/PGS000737/ indicates a sample size of 1,427 individuals.

however, in the source publication [10.1093/eurheartj/ehz435](https://academic.oup.com/eurheartj/article/40/37/3097/5559542), I only find the numbers 1,400 and 1,368 after filtering.

Mistake here?

**Comment by smlmbrt** [comment]
Hi @ramiromagno, we double-checked the numbers and don't think it's a mistake. The GWAS used in this paper came from a previous study (PMID:23872634) that included 1427 individuals. In this paper the total sample size after QC was 1368 individuals, of which 1185 had Brugada syndrome (shown in the performance metrics, Figure 3A in the paper). Hopefully that clarifies, let me know!

**Comment by ramiromagno** [comment]
You are right, thank you!
