### ISSUE TITLE
Recode "NR" as null in method_params

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#180]
```bash
curl -s -X GET "https://www.pgscatalog.org/rest/score/PGS000737?format=json" -H  "accept: application/json" | jq '.' | grep method_params
```

```
"method_params": "NR",
```

**Comment by ens-lgil** [comment]
Dear @ramiromagno,

Thanks again for reporting this. This makes sense to have a `null` value here.
We are going to fix it in the database, therefore the change will be in our next release (normally within the next 2 weeks).

Best regards,
Laurent

**Comment by ens-lgil** [comment]
Dear @ramiromagno,

A late message to confirm that we removed the **NR** values in the `method_params` field. 

Best regards,
Laurent
