### ISSUE TITLE
Provide population reference calculations and distributions

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#187]
Hi PGS Catalog team

This is a feature request.

While answering one of the comments to your medRxiv preprint, @smlmbrt mentioned that you were *"(...) exploring ways to to add population reference calculations and distributions (e.g. percentiles) to aid end-user applications and interpretation , and hope to add those features in the future."* (from a [reply to Charles Warden](https://www.medrxiv.org/content/10.1101/2020.05.20.20108217v1#disqus_thread)).

So, I am just adding this request here to GitHub issues to keep track of its progress.

**Comment by smlmbrt** [comment]
Definitely in the works. This involves tooling:
- Sample -> Ancestry matching (e.g. by PCA to reference)
- Sample -> PGS Calculation (depends on data-formats)
- Sample-specific PGS -> Population percentile (and which distributions/datasets to use) 

If you have pointers to standard libraries/existing tools you think would be useful I'd be happy to take a look.

**Comment by smlmbrt** [comment]
This is being developed within https://github.com/PGScatalog/pgsc_calc

**Comment by smlmbrt** [comment]
Adjustment is implemented in v2 of the `pgsc_calc` tool : https://github.com/PGScatalog/pgsc_calc
