### ISSUE TITLE
500 Internal Server Error with `https://www.pgscatalog.org/rest/score/search?pmid=PGP000003&format=json`

### ISSUE THREAD

**Issue by ramiromagno** [PGScatalog/PGS_Catalog#213]
`https://www.pgscatalog.org/rest/score/search?pmid=PGP000003&format=json` triggers a 500 Internal Server Error.

NB: While I do understand that PGP000003 is a not a possible value for `pmid`, the error shouldn't be an internal server error nevertheless.

**Comment by ens-lgil** [comment]
Dear @ramiromagno,

Thank you for spotting this issue!
We recently change the way we store the PubMed IDs in the database (was stored as a string and now it's stored as a numeric value), and the REST API is now expecting a numeric value for the `pmid` parameter.
I am going to fix it.

Best regards,
Laurent
