### ISSUE TITLE
Curation tracker

### ISSUE THREAD

**Issue by smlmbrt** [PGScatalog/PGS_Catalog#257]
Create django admin infrastructure to track and annotate PGS Catalog publication eligibility and curation status. Requirements:
- Allow input from multiple sources (LitSuggest, manual entry of studies)
- Should let us know the curation queue (awaiting L1/L2)
- Should allow management/release of studies and embargoed data to the curation DB and live server

**Comment by ens-lgil** [comment]
New to create a PR and merge the new code to the master branch

**Comment by ens-lgil** [comment]
Done!
