### ISSUE TITLE
What are "Covariates Included in the Model?"

### ISSUE THREAD

**Issue by Fiwx** [PGScatalog/PGS_Catalog#277]
If we go [here](https://www.pgscatalog.org/score/PGS003725/), we see "age, sex and the first ten principal components of genetic ancestry" are controlled for in performance metrics. Other PGSs have more or less.

Are the covariates (as reported in the PGS Catalog):
- A: Variables which are controlled for in the performance calculation (for example, so as not include genetic sex differences in the model, so the performance doesn't reflect the effect of sex). This means including sex as a covariate could decrease the reported performance of the model, and having this covariate might make us relatively more confident in the robustness of the model. The final model removes the effect of the covariates so that ~only the PGS is used assess performance.
- B: Variables which are added to the model, such that the performance calculation includes the effects of these variables. That is, the performance metric might increase if one included sex (if sex is relevant to the phenotype prediction). Including covariates in this way would make us less certain of the accuracy of the polygenic score alone. The final model uses the effect of both the covariates and the PGS to achieve performance.
- C: Indeterminate. Authors choose either A or B, and one must try to glean the information from the individual paper.

An example of the question that A could answer is "how well does PRS predict without the effect of X Y Z known risk factors?"
An example of the question that B could answer is "how much does a model with both PRS and X Y Z known risk factors predict?"

I believe it is A, but I wanted to verify that it is not C. Thank you.

**Comment by smlmbrt** [comment]
The answer is C, but the most common analysis is probably B (phenotype ~ age + sex + PCs + PGS/PRS). The effect size metrics are specific to the PGS of study (e.g. change in risk/trait per unit change in PGS) and contextualised with the covariates listed. The classification metrics (AUROC/C-index) and variance explained (R2) are in relation to the full model and not the PRS alone (unless there are no covariates). When possible (or submitted) we split the data from different models across rows differing by covariates, or add information about relative performance metrics in the Other Metrics column - this is quite unstructured though as the data we extract is very heterogenous.
