### ISSUE TITLE
Incorrect Categorisation

### ISSUE THREAD

**Issue by DarioS** [PGScatalog/PGS_Catalog#294]
PGS002777 and PGS002778 should be in [EFO_0000537](https://www.pgscatalog.org/trait/EFO_0000537/) and not in [EFO_0001645](https://www.pgscatalog.org/trait/EFO_0001645/), shouldn't they? Correlation of these two is about 0 with all other EFO_0001645 members but all other scores are highly positively correlated with each other.

**Comment by smlmbrt** [comment]
Hi @DarioS, good catch! We will correct these in the next release.

Sam

**Comment by ens-lgil** [comment]
Fixed
