### ISSUE TITLE
Add new traits to release dashboard

### ISSUE THREAD

**Issue by fyvon** [PGScatalog/PGS_Catalog#336]

**Comment by ens-lgil** [comment]
You could use the method written here as a starting point: https://github.com/PGScatalog/PGS_Catalog/blob/master/release/scripts/run_post_processing_script.py#L79
However I am not sure that the line `if count_scores == 1:` is correct, mainly if more than one new score is mapped to a new trait.
Furthermore, this method is used after the cleanup of the DB.

One thing we could do is to fetch the list of traits from the new release and check if they are mapped to any scores released before this new release
