### ISSUE TITLE
Harmonized files for PGS002759 contain information from another score?

### ISSUE THREAD

**Issue by smlmbrt** [PGScatalog/PGS_Catalog#386]
It seems like for PGS002759 the formatted scoring file is correct (contain expected data from Mars et al); however the harmonised files contain the harmonised data for PGS000767 from Guffanti et al. I assume this was an FTP copying error, but need to track down:

- [x] correct scoring file for PGS002759
- [x] check that this doesn't effect other sets of harmonised files (reading headers and comparing with folders)

Original report:
> For point 2: I was able to replicate this issue, which the attached screenshot of the score report demonstrates; although I specified PGS002759 in the command, it seems the scoring file pulled was PGS000767.
> ![Screenshot 2024-09-10 at 11 29 23 AM](https://github.com/user-attachments/assets/c855d3c9-696f-4ea0-ba42-1bf92deda46e)

_Originally posted by @Sabramow in https://github.com/PGScatalog/pgsc_calc/issues/370#issuecomment-2341263767_

**Comment by ens-lgil** [comment]
The 37 and 38 harmonized files for `PGS002759` have been regenerated and copied to the Public FTP and production directories.

**Comment by ens-lgil** [comment]
I compared the Harmonized file headers vs Harmonized file names for each PGS ID, and it looks ok for all of them: the PGS IDs in the header rows `#pgs_id=PGS00XXXX` match the PGS IDs of the harmonized file names `PGS00XXXX_hmPOS_GRCh37.txt.gz` and `PGS00XXXX_hmPOS_GRCh38.txt.gz` across the Catalog

**Comment by smlmbrt** [comment]
Should we also double-check number of variants to be extra sure?

S
