### ISSUE TITLE
Highlight when publication is a preprint

### ISSUE THREAD

**Issue by smlmbrt** [PGScatalog/PGS_Catalog#66]
We should have a flag, badge, or something that marks a Publication as a preprint. Maybe a button with hover text that explains what a preprint is: "manuscript has not undergone peer review"

**Comment by smlmbrt** [comment]
- [ ] On the Publication page the header could change to “PGS Preprint: PGP…“, and a button/badge could appear beside the Journal in the table

- [ ] Appear as a badge/button (perhaps PRP or PP) beside the text things like “PGP000050 
 Graff RE et al. bioRxiv (2020)” in Tables (_if possible_)

**Comment by ens-lgil** [comment]
Does it apply to the publications without **PMID** and/or **doi** ?

**Comment by smlmbrt** [comment]
In our case let’s do it by journal name =  bioRxiv or medRxiv. We could make it a model field (true/false) and set this when we import publications? The information can also be extracted from EuropePMC.

**Comment by ens-lgil** [comment]
Highlight added to the codebase and pushed to the live website
